kubectl apply -f - <<EOF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: wpgp3
  resources:
    requests:
      storage: 3Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wpgp3
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
allowVolumeExpansion: true 
EOF
